StrVec
using StrVec::size_t = unsigned int
allocator<string> StrVec::alloc
Referenced by alloc_n_copy, free, push_back, reallocate.
string* StrVec::_elments
Referenced by free, StrVec.
string* StrVec::_first_free
Referenced by free, push_back, StrVec.
string* StrVec::_cap
Referenced by StrVec.
StrVec::StrVec()
StrVec::StrVec(const StrVec &copyobj)
References _cap, _elments, _first_free, alloc_n_copy.
StrVec & StrVec::operator=(const StrVec &right)
StrVec::~StrVec()
References free.
void StrVec::push_back(string &str)
References _first_free, alloc, chk_n_alloc.
size_t StrVec::size() const
Referenced by free, reallocate.
size_t StrVec::capacity() const
string* StrVec::begin() const
string* StrVec::end() const
void StrVec::chk_n_alloc()
Referenced by push_back.
pair< string *, string * > StrVec::alloc_n_copy(const string *, const string *)
References alloc.
Referenced by StrVec.
void StrVec::free()
References _elments, _first_free, alloc, size.
Referenced by ~StrVec.
void StrVec::reallocate()
References alloc, size.