Vec
T* Vec< T >::element
data members
Referenced by Vec< T >::begin, Vec< T >::capacity, Vec< T >::size.
T* Vec< T >::first_free
Referenced by Vec< T >::end, Vec< T >::size.
T* Vec< T >::cap
Referenced by Vec< T >::capacity.
std::allocator<T> Vec< T >::alloc
Vec< T >::Vec()
Vec< T >::Vec(std::initializer_list< T > l)
constructor that takes initializer_list<T>
Vec< T >::Vec(const Vec &v)
copy constructor
References Vec< T >::begin, Vec< T >::end.
Vec< T > & Vec< T >::operator=(const Vec &rhs)
operator =
References Vec< T >::begin, Vec< T >::end.
Vec< T >::~Vec()
destructor
void Vec< T >::push_back(const T &t)
memmbers
allocate new memeory if nessary and push back the new T t new T
Referenced by main.
std::size_t Vec< T >::size() const
References Vec< T >::element, Vec< T >::first_free.
Referenced by Vec< T >::chk_n_alloc.
std::size_t Vec< T >::capacity() const
References Vec< T >::cap, Vec< T >::element.
Referenced by Vec< T >::chk_n_alloc, main.
T* Vec< T >::begin() const
References Vec< T >::element.
Referenced by Vec< T >::operator=, Vec< T >::Vec.
T* Vec< T >::end() const
References Vec< T >::first_free.
Referenced by Vec< T >::operator=, Vec< T >::Vec.
void Vec< T >::reserve(std::size_t n)
preallocate enough memory for specified number of elements
n number of elements required
void Vec< T >::resize(std::size_t n)
Resizes to the specified number of elements.
n Number of elements the vector should contain. This function will resize it to the specified number of elements. If the number is smaller than the current size it is truncated, otherwise default constructed elements are appended.
Referenced by main.
void Vec< T >::resize(std::size_t n, const T &t)
Resizes it to the specified number of elements.
__new_size Number of elements it should contain. __x Data with which new elements should be populated. This function will resize it to the specified number of elements. If the number is smaller than the current size the it is truncated, otherwise the it is extended and new elements are populated with given data.
void Vec< T >::reallocate()
utillities
Double the capacity and using std::move move the original data to the newly allocated memory.
Referenced by Vec< T >::chk_n_alloc.
void Vec< T >::chk_n_alloc()
References Vec< T >::capacity, Vec< T >::reallocate, Vec< T >::size.
void Vec< T >::free()
destroy the elements and deallocate the space previously allocated.
void Vec< T >::wy_alloc_n_move(std::size_t n)
allocate memory for spicified number of elements
n it's user's responsibility to ensure that n is greater than the current capacity.
std::pair< T *, T * > Vec< T >::alloc_n_copy(T *b, T *e)
allocate new space for the given range and copy them into it
b e a pair of pointers pointing to [first element , one past the last) in the new space