movable.cpp
HasPtrMem getTemp()
Referenced by main1.
void main1()
References HasPtrMem::_d, a, b, c, getTemp.
Moveable getTemp2()
Referenced by main2.
void main2()
References a, getTemp2.
Referenced by main3.
int main3(int argc, char *argv[])
References main2.
void forwardValue(T &val)
References __processValue.
Referenced by main.
void __processValue(T &&val)
Referenced by forwardValue, main.
int main()
References __processValue, forwardValue.