perfect forwarding.cpp
void f2(int &m)
Referenced by f1.
void f2(int &&m)
void f2(const int &m)
void f2(const int &&m)
void f1(T &&t)
References f2.
Referenced by main.
void f3(int &&t)
Referenced by main.
int main(int argc, char *argv[])
References a, b, c, f1, f3.
void foo(int &m)
void bar()
References a, a2, b, c.